In [1]:
import numpy as np

x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9],], 
              [[11, 12, 13], [14, 15, 16], [17, 18, 19],],
              [[21, 22, 23], [24, 25 ,26], [27, 28, 29]]])


print("Whole array")
print(x)

print("\nArray: secound row and second collumn.")
print(x[1, 1])

print("\nArray: in each column, secound row, each secound variable.")
print(x[:, 1, 1])

print("\nArray: in secound column, in each row, each secound variable.")
print(x[1, :, 1])

print("\nArray: for secound collumn and the range from secound to third row.")
print(x[2, 1:3])

Whole array
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]

Array: secound row and second collumn.
[14 15 16]

Array: in each column, secound row, each secound variable.
[ 5 15 25]

Array: in secound column, in each row, each secound variable.
[12 15 18]

Array: for secound collumn and the range from secound to third row.
[[24 25 26]
 [27 28 29]]
